<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Aggregators\" />
    <Folder Include="Contracts\" />
    <Folder Include="DomainServices\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ESCMB.GameCore" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Domain\Core.Domain.csproj" />
  </ItemGroup>

</Project>
