// <auto-generated />
using Infrastructure.Repositories.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.Sqlite
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20251001045534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Domain.Entities.Alumno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("TEXT");

                    b.Property<string>("DNI")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Legajo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Automovil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fabricacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroChasis")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroMotor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroChasis")
                        .IsUnique();

                    b.HasIndex("NumeroMotor")
                        .IsUnique();

                    b.ToTable("Automoviles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
